### ISSUE TITLE
On bow use, generating null execptions

### ISSUE THREAD

**Issue by wvbigdave** [Indyuce/moar-bows#6]
Anytime anyone uses the bows, I get null exceptions that fill the logs.

https://pastebin.com/7k6iQXTR

This occurs but the bows still work.

**Comment by wvbigdave** [comment]
I just posted the same one 3 days ago. no response yet.

**Comment by Indyuce** [comment]
Please paste the full server logs

**Comment by sitdownrightnow2552** [comment]
I'm facing the same issue with silver bow
```
[18:43:08 ERROR]: Could not pass event EntityDamageByEntityEvent to MoarBows v2.5.5
java.lang.NullPointerException: null
        at net.Indyuce.moarbows.api.MoarBow.getDouble(MoarBow.java:116) ~[?:?]
        at net.Indyuce.moarbows.api.ArrowData.getDouble(ArrowData.java:84) ~[?:?]
        at net.Indyuce.moarbows.bow.Silver_Bow.whenHit(Silver_Bow.java:38) ~[?:?]
        at net.Indyuce.moarbows.listener.HitEntity.a(HitEntity.java:27) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-387]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:240) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1008) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:895) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:851) ~[patched_1.15.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1040) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity0(EntityLiving.java:1691) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1049) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:378) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:291) ~[patched_1.15.2.jar:git-Paper-387]
        at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:202) ~[patched_1.15.2.jar:git-Paper-387]
```

**Comment by Indyuce** [comment]
It does not look like the same issue. Can you please provide the full latest server logs including MoarBows startup logs as well as the same issue you posted above?

**Comment by sitdownrightnow2552** [comment]
i found the problem, please take a look at my [pull request](https://github.com/Indyuce/moar-bows/pull/8)

**Comment by Indyuce** [comment]
Apologies for the late fix, a fix will be published later today
